// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: pod_service.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pod 状态枚举
type PodState int32

const (
	PodState_PENDING   PodState = 0
	PodState_RUNNING   PodState = 1
	PodState_SUCCEEDED PodState = 2
	PodState_FAILED    PodState = 3
	PodState_UNKNOWN   PodState = 4
)

// Enum value maps for PodState.
var (
	PodState_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "SUCCEEDED",
		3: "FAILED",
		4: "UNKNOWN",
	}
	PodState_value = map[string]int32{
		"PENDING":   0,
		"RUNNING":   1,
		"SUCCEEDED": 2,
		"FAILED":    3,
		"UNKNOWN":   4,
	}
)

func (x PodState) Enum() *PodState {
	p := new(PodState)
	*p = x
	return p
}

func (x PodState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PodState) Descriptor() protoreflect.EnumDescriptor {
	return file_pod_service_proto_enumTypes[0].Descriptor()
}

func (PodState) Type() protoreflect.EnumType {
	return &file_pod_service_proto_enumTypes[0]
}

func (x PodState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PodState.Descriptor instead.
func (PodState) EnumDescriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{0}
}

// Pod 基本信息
type Pod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	State         PodState               `protobuf:"varint,3,opt,name=state,proto3,enum=pod.v1alpha1.PodState" json:"state,omitempty"`
	NodeName      string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PodIp         string                 `protobuf:"bytes,5,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_pod_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{0}
}

func (x *Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Pod) GetState() PodState {
	if x != nil {
		return x.State
	}
	return PodState_PENDING
}

func (x *Pod) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Pod) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *Pod) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Pod) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Pod) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// 删除 Pod 请求
type DeletePodRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Namespace          string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName            string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Force              bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	GracePeriodSeconds int64                  `protobuf:"varint,4,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeletePodRequest) Reset() {
	*x = DeletePodRequest{}
	mi := &file_pod_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePodRequest) ProtoMessage() {}

func (x *DeletePodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePodRequest.ProtoReflect.Descriptor instead.
func (*DeletePodRequest) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeletePodRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeletePodRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *DeletePodRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *DeletePodRequest) GetGracePeriodSeconds() int64 {
	if x != nil {
		return x.GracePeriodSeconds
	}
	return 0
}

// 删除 Pod 响应
type DeletePodResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Message           string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	DeletionTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deletion_timestamp,json=deletionTimestamp,proto3" json:"deletion_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeletePodResponse) Reset() {
	*x = DeletePodResponse{}
	mi := &file_pod_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePodResponse) ProtoMessage() {}

func (x *DeletePodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePodResponse.ProtoReflect.Descriptor instead.
func (*DeletePodResponse) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeletePodResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeletePodResponse) GetDeletionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionTimestamp
	}
	return nil
}

// 获取 Pod 日志请求
type GetPodLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	Follow        bool                   `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"`
	Previous      bool                   `protobuf:"varint,5,opt,name=previous,proto3" json:"previous,omitempty"`
	SinceSeconds  int64                  `protobuf:"varint,6,opt,name=since_seconds,json=sinceSeconds,proto3" json:"since_seconds,omitempty"`
	TailLines     int64                  `protobuf:"varint,7,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	Timestamps    bool                   `protobuf:"varint,8,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodLogsRequest) Reset() {
	*x = GetPodLogsRequest{}
	mi := &file_pod_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodLogsRequest) ProtoMessage() {}

func (x *GetPodLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodLogsRequest.ProtoReflect.Descriptor instead.
func (*GetPodLogsRequest) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetPodLogsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetPodLogsRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *GetPodLogsRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *GetPodLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *GetPodLogsRequest) GetPrevious() bool {
	if x != nil {
		return x.Previous
	}
	return false
}

func (x *GetPodLogsRequest) GetSinceSeconds() int64 {
	if x != nil {
		return x.SinceSeconds
	}
	return 0
}

func (x *GetPodLogsRequest) GetTailLines() int64 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *GetPodLogsRequest) GetTimestamps() bool {
	if x != nil {
		return x.Timestamps
	}
	return false
}

// 日志数据块
type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_pod_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{4}
}

func (x *LogChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *LogChunk) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// 终端会话信息，应在流的第一个消息中发送
type TerminalSessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"` // 可选
	Command       []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`     // 可选, e.g., ["/bin/sh"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSessionInfo) Reset() {
	*x = TerminalSessionInfo{}
	mi := &file_pod_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSessionInfo) ProtoMessage() {}

func (x *TerminalSessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSessionInfo.ProtoReflect.Descriptor instead.
func (*TerminalSessionInfo) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{5}
}

func (x *TerminalSessionInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TerminalSessionInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *TerminalSessionInfo) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *TerminalSessionInfo) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

// 终端消息
type TerminalMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TerminalMessage_SessionInfo
	//	*TerminalMessage_Data
	//	*TerminalMessage_Resize
	Payload       isTerminalMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalMessage) Reset() {
	*x = TerminalMessage{}
	mi := &file_pod_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalMessage) ProtoMessage() {}

func (x *TerminalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalMessage.ProtoReflect.Descriptor instead.
func (*TerminalMessage) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{6}
}

func (x *TerminalMessage) GetPayload() isTerminalMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TerminalMessage) GetSessionInfo() *TerminalSessionInfo {
	if x != nil {
		if x, ok := x.Payload.(*TerminalMessage_SessionInfo); ok {
			return x.SessionInfo
		}
	}
	return nil
}

func (x *TerminalMessage) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*TerminalMessage_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *TerminalMessage) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Payload.(*TerminalMessage_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isTerminalMessage_Payload interface {
	isTerminalMessage_Payload()
}

type TerminalMessage_SessionInfo struct {
	SessionInfo *TerminalSessionInfo `protobuf:"bytes,1,opt,name=session_info,json=sessionInfo,proto3,oneof"` // 客户端发送的第一个消息
}

type TerminalMessage_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // 客户端 -> 服务端: stdin; 服务端 -> 客户端: stdout/stderr
}

type TerminalMessage_Resize struct {
	Resize *Resize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"` // 客户端发送的窗口大小调整
}

func (*TerminalMessage_SessionInfo) isTerminalMessage_Payload() {}

func (*TerminalMessage_Data) isTerminalMessage_Payload() {}

func (*TerminalMessage_Resize) isTerminalMessage_Payload() {}

// 终端窗口大小
type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_pod_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{7}
}

func (x *Resize) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Resize) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// 配置 HPA 请求
type ConfigureHPARequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Namespace            string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName       string                 `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	MinReplicas          int32                  `protobuf:"varint,3,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	MaxReplicas          int32                  `protobuf:"varint,4,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas,omitempty"`
	Metrics              map[string]string      `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TargetCpuUtilization int32                  `protobuf:"varint,6,opt,name=target_cpu_utilization,json=targetCpuUtilization,proto3" json:"target_cpu_utilization,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConfigureHPARequest) Reset() {
	*x = ConfigureHPARequest{}
	mi := &file_pod_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureHPARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureHPARequest) ProtoMessage() {}

func (x *ConfigureHPARequest) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureHPARequest.ProtoReflect.Descriptor instead.
func (*ConfigureHPARequest) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigureHPARequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConfigureHPARequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *ConfigureHPARequest) GetMinReplicas() int32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *ConfigureHPARequest) GetMaxReplicas() int32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

func (x *ConfigureHPARequest) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ConfigureHPARequest) GetTargetCpuUtilization() int32 {
	if x != nil {
		return x.TargetCpuUtilization
	}
	return 0
}

// 配置 HPA 响应
type ConfigureHPAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureHPAResponse) Reset() {
	*x = ConfigureHPAResponse{}
	mi := &file_pod_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureHPAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureHPAResponse) ProtoMessage() {}

func (x *ConfigureHPAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureHPAResponse.ProtoReflect.Descriptor instead.
func (*ConfigureHPAResponse) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigureHPAResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigureHPAResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 配置 VPA 请求
type ConfigureVPARequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Namespace        string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName   string                 `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	UpdateMode       bool                   `protobuf:"varint,3,opt,name=update_mode,json=updateMode,proto3" json:"update_mode,omitempty"`
	ResourcePolicies map[string]string      `protobuf:"bytes,4,rep,name=resource_policies,json=resourcePolicies,proto3" json:"resource_policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigureVPARequest) Reset() {
	*x = ConfigureVPARequest{}
	mi := &file_pod_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureVPARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureVPARequest) ProtoMessage() {}

func (x *ConfigureVPARequest) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureVPARequest.ProtoReflect.Descriptor instead.
func (*ConfigureVPARequest) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigureVPARequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConfigureVPARequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *ConfigureVPARequest) GetUpdateMode() bool {
	if x != nil {
		return x.UpdateMode
	}
	return false
}

func (x *ConfigureVPARequest) GetResourcePolicies() map[string]string {
	if x != nil {
		return x.ResourcePolicies
	}
	return nil
}

// 配置 VPA 响应
type ConfigureVPAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureVPAResponse) Reset() {
	*x = ConfigureVPAResponse{}
	mi := &file_pod_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureVPAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureVPAResponse) ProtoMessage() {}

func (x *ConfigureVPAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureVPAResponse.ProtoReflect.Descriptor instead.
func (*ConfigureVPAResponse) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigureVPAResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigureVPAResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 创建金丝雀部署请求
type CreateCanaryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	RolloutName    string                 `protobuf:"bytes,2,opt,name=rollout_name,json=rolloutName,proto3" json:"rollout_name,omitempty"`
	ReplicaCount   int32                  `protobuf:"varint,3,opt,name=replica_count,json=replicaCount,proto3" json:"replica_count,omitempty"`
	Image          string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Selector       map[string]string      `protobuf:"bytes,5,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TrafficRouting map[string]string      `protobuf:"bytes,6,rep,name=traffic_routing,json=trafficRouting,proto3" json:"traffic_routing,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Steps          int32                  `protobuf:"varint,7,opt,name=steps,proto3" json:"steps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCanaryRequest) Reset() {
	*x = CreateCanaryRequest{}
	mi := &file_pod_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCanaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCanaryRequest) ProtoMessage() {}

func (x *CreateCanaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCanaryRequest.ProtoReflect.Descriptor instead.
func (*CreateCanaryRequest) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{12}
}

func (x *CreateCanaryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateCanaryRequest) GetRolloutName() string {
	if x != nil {
		return x.RolloutName
	}
	return ""
}

func (x *CreateCanaryRequest) GetReplicaCount() int32 {
	if x != nil {
		return x.ReplicaCount
	}
	return 0
}

func (x *CreateCanaryRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateCanaryRequest) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *CreateCanaryRequest) GetTrafficRouting() map[string]string {
	if x != nil {
		return x.TrafficRouting
	}
	return nil
}

func (x *CreateCanaryRequest) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

// 创建金丝雀部署响应
type CreateCanaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCanaryResponse) Reset() {
	*x = CreateCanaryResponse{}
	mi := &file_pod_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCanaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCanaryResponse) ProtoMessage() {}

func (x *CreateCanaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCanaryResponse.ProtoReflect.Descriptor instead.
func (*CreateCanaryResponse) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCanaryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCanaryResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 创建蓝绿部署请求
type CreateBlueGreenRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Namespace            string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	RolloutName          string                 `protobuf:"bytes,2,opt,name=rollout_name,json=rolloutName,proto3" json:"rollout_name,omitempty"`
	ActiveService        string                 `protobuf:"bytes,3,opt,name=active_service,json=activeService,proto3" json:"active_service,omitempty"`
	PreviewService       string                 `protobuf:"bytes,4,opt,name=preview_service,json=previewService,proto3" json:"preview_service,omitempty"`
	Image                string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	ReplicaCount         int32                  `protobuf:"varint,6,opt,name=replica_count,json=replicaCount,proto3" json:"replica_count,omitempty"`
	Selector             map[string]string      `protobuf:"bytes,7,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AutoPromotionEnabled bool                   `protobuf:"varint,8,opt,name=auto_promotion_enabled,json=autoPromotionEnabled,proto3" json:"auto_promotion_enabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateBlueGreenRequest) Reset() {
	*x = CreateBlueGreenRequest{}
	mi := &file_pod_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlueGreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlueGreenRequest) ProtoMessage() {}

func (x *CreateBlueGreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlueGreenRequest.ProtoReflect.Descriptor instead.
func (*CreateBlueGreenRequest) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{14}
}

func (x *CreateBlueGreenRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateBlueGreenRequest) GetRolloutName() string {
	if x != nil {
		return x.RolloutName
	}
	return ""
}

func (x *CreateBlueGreenRequest) GetActiveService() string {
	if x != nil {
		return x.ActiveService
	}
	return ""
}

func (x *CreateBlueGreenRequest) GetPreviewService() string {
	if x != nil {
		return x.PreviewService
	}
	return ""
}

func (x *CreateBlueGreenRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateBlueGreenRequest) GetReplicaCount() int32 {
	if x != nil {
		return x.ReplicaCount
	}
	return 0
}

func (x *CreateBlueGreenRequest) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *CreateBlueGreenRequest) GetAutoPromotionEnabled() bool {
	if x != nil {
		return x.AutoPromotionEnabled
	}
	return false
}

// 创建蓝绿部署响应
type CreateBlueGreenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlueGreenResponse) Reset() {
	*x = CreateBlueGreenResponse{}
	mi := &file_pod_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlueGreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlueGreenResponse) ProtoMessage() {}

func (x *CreateBlueGreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlueGreenResponse.ProtoReflect.Descriptor instead.
func (*CreateBlueGreenResponse) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateBlueGreenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateBlueGreenResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 获取应用列表下所有pod的资源
type PodsMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ReleaseName   string                 `protobuf:"bytes,2,opt,name=release_name,json=releaseName,proto3" json:"release_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodsMetricsRequest) Reset() {
	*x = PodsMetricsRequest{}
	mi := &file_pod_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodsMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodsMetricsRequest) ProtoMessage() {}

func (x *PodsMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodsMetricsRequest.ProtoReflect.Descriptor instead.
func (*PodsMetricsRequest) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{16}
}

func (x *PodsMetricsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodsMetricsRequest) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

type PodsMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	AppNum        int32                  `protobuf:"varint,2,opt,name=app_num,json=appNum,proto3" json:"app_num,omitempty"`
	PodNum        int32                  `protobuf:"varint,3,opt,name=pod_num,json=podNum,proto3" json:"pod_num,omitempty"`
	CpuUsage      string                 `protobuf:"bytes,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemUsage      string                 `protobuf:"bytes,5,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodsMetricsResponse) Reset() {
	*x = PodsMetricsResponse{}
	mi := &file_pod_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodsMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodsMetricsResponse) ProtoMessage() {}

func (x *PodsMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pod_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodsMetricsResponse.ProtoReflect.Descriptor instead.
func (*PodsMetricsResponse) Descriptor() ([]byte, []int) {
	return file_pod_service_proto_rawDescGZIP(), []int{17}
}

func (x *PodsMetricsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PodsMetricsResponse) GetAppNum() int32 {
	if x != nil {
		return x.AppNum
	}
	return 0
}

func (x *PodsMetricsResponse) GetPodNum() int32 {
	if x != nil {
		return x.PodNum
	}
	return 0
}

func (x *PodsMetricsResponse) GetCpuUsage() string {
	if x != nil {
		return x.CpuUsage
	}
	return ""
}

func (x *PodsMetricsResponse) GetMemUsage() string {
	if x != nil {
		return x.MemUsage
	}
	return ""
}

var File_pod_service_proto protoreflect.FileDescriptor

const file_pod_service_proto_rawDesc = "" +
	"\n" +
	"\x11pod_service.proto\x12\fpod.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x03\n" +
	"\x03Pod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12,\n" +
	"\x05state\x18\x03 \x01(\x0e2\x16.pod.v1alpha1.PodStateR\x05state\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12\x15\n" +
	"\x06pod_ip\x18\x05 \x01(\tR\x05podIp\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\x06labels\x18\a \x03(\v2\x1d.pod.v1alpha1.Pod.LabelsEntryR\x06labels\x12D\n" +
	"\vannotations\x18\b \x03(\v2\".pod.v1alpha1.Pod.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\x10DeletePodRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\x120\n" +
	"\x14grace_period_seconds\x18\x04 \x01(\x03R\x12gracePeriodSeconds\"x\n" +
	"\x11DeletePodResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12I\n" +
	"\x12deletion_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x11deletionTimestamp\"\x82\x02\n" +
	"\x11GetPodLogsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\x12\x16\n" +
	"\x06follow\x18\x04 \x01(\bR\x06follow\x12\x1a\n" +
	"\bprevious\x18\x05 \x01(\bR\bprevious\x12#\n" +
	"\rsince_seconds\x18\x06 \x01(\x03R\fsinceSeconds\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\a \x01(\x03R\ttailLines\x12\x1e\n" +
	"\n" +
	"timestamps\x18\b \x01(\bR\n" +
	"timestamps\"^\n" +
	"\bLogChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x86\x01\n" +
	"\x13TerminalSessionInfo\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\"\xaa\x01\n" +
	"\x0fTerminalMessage\x12F\n" +
	"\fsession_info\x18\x01 \x01(\v2!.pod.v1alpha1.TerminalSessionInfoH\x00R\vsessionInfo\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12.\n" +
	"\x06resize\x18\x03 \x01(\v2\x14.pod.v1alpha1.ResizeH\x00R\x06resizeB\t\n" +
	"\apayload\"6\n" +
	"\x06Resize\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\"\xde\x02\n" +
	"\x13ConfigureHPARequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12'\n" +
	"\x0fdeployment_name\x18\x02 \x01(\tR\x0edeploymentName\x12!\n" +
	"\fmin_replicas\x18\x03 \x01(\x05R\vminReplicas\x12!\n" +
	"\fmax_replicas\x18\x04 \x01(\x05R\vmaxReplicas\x12H\n" +
	"\ametrics\x18\x05 \x03(\v2..pod.v1alpha1.ConfigureHPARequest.MetricsEntryR\ametrics\x124\n" +
	"\x16target_cpu_utilization\x18\x06 \x01(\x05R\x14targetCpuUtilization\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x14ConfigureHPAResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa8\x02\n" +
	"\x13ConfigureVPARequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12'\n" +
	"\x0fdeployment_name\x18\x02 \x01(\tR\x0edeploymentName\x12\x1f\n" +
	"\vupdate_mode\x18\x03 \x01(\bR\n" +
	"updateMode\x12d\n" +
	"\x11resource_policies\x18\x04 \x03(\v27.pod.v1alpha1.ConfigureVPARequest.ResourcePoliciesEntryR\x10resourcePolicies\x1aC\n" +
	"\x15ResourcePoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x14ConfigureVPAResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd4\x03\n" +
	"\x13CreateCanaryRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12!\n" +
	"\frollout_name\x18\x02 \x01(\tR\vrolloutName\x12#\n" +
	"\rreplica_count\x18\x03 \x01(\x05R\freplicaCount\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12K\n" +
	"\bselector\x18\x05 \x03(\v2/.pod.v1alpha1.CreateCanaryRequest.SelectorEntryR\bselector\x12^\n" +
	"\x0ftraffic_routing\x18\x06 \x03(\v25.pod.v1alpha1.CreateCanaryRequest.TrafficRoutingEntryR\x0etrafficRouting\x12\x14\n" +
	"\x05steps\x18\a \x01(\x05R\x05steps\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13TrafficRoutingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x14CreateCanaryResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa7\x03\n" +
	"\x16CreateBlueGreenRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12!\n" +
	"\frollout_name\x18\x02 \x01(\tR\vrolloutName\x12%\n" +
	"\x0eactive_service\x18\x03 \x01(\tR\ractiveService\x12'\n" +
	"\x0fpreview_service\x18\x04 \x01(\tR\x0epreviewService\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12#\n" +
	"\rreplica_count\x18\x06 \x01(\x05R\freplicaCount\x12N\n" +
	"\bselector\x18\a \x03(\v22.pod.v1alpha1.CreateBlueGreenRequest.SelectorEntryR\bselector\x124\n" +
	"\x16auto_promotion_enabled\x18\b \x01(\bR\x14autoPromotionEnabled\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x17CreateBlueGreenResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"U\n" +
	"\x12PodsMetricsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12!\n" +
	"\frelease_name\x18\x02 \x01(\tR\vreleaseName\"\x95\x01\n" +
	"\x13PodsMetricsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x17\n" +
	"\aapp_num\x18\x02 \x01(\x05R\x06appNum\x12\x17\n" +
	"\apod_num\x18\x03 \x01(\x05R\x06podNum\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\tR\bcpuUsage\x12\x1b\n" +
	"\tmem_usage\x18\x05 \x01(\tR\bmemUsage*L\n" +
	"\bPodState\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\r\n" +
	"\tSUCCEEDED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\v\n" +
	"\aUNKNOWN\x10\x042\xcf\t\n" +
	"\x11PodManagerService\x12\x86\x01\n" +
	"\tDeletePod\x12\x1e.pod.v1alpha1.DeletePodRequest\x1a\x1f.pod.v1alpha1.DeletePodResponse\"8\x82\xd3\xe4\x93\x022*0/v1alpha1/namespaces/{namespace}/pods/{pod_name}\x12\x86\x01\n" +
	"\n" +
	"GetPodLogs\x12\x1f.pod.v1alpha1.GetPodLogsRequest\x1a\x16.pod.v1alpha1.LogChunk\"=\x82\xd3\xe4\x93\x027\x125/v1alpha1/namespaces/{namespace}/pods/{pod_name}/logs0\x01\x12r\n" +
	"\x0fExecPodTerminal\x12\x1d.pod.v1alpha1.TerminalMessage\x1a\x1d.pod.v1alpha1.TerminalMessage\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1alpha1/pod/exec(\x010\x01\x12\x98\x01\n" +
	"\x1eConfigureHorizontalAutoscaling\x12!.pod.v1alpha1.ConfigureHPARequest\x1a\".pod.v1alpha1.ConfigureHPAResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1alpha1/namespaces/{namespace}/hpa\x12\x96\x01\n" +
	"\x1cConfigureVerticalAutoscaling\x12!.pod.v1alpha1.ConfigureVPARequest\x1a\".pod.v1alpha1.ConfigureVPAResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1alpha1/namespaces/{namespace}/vpa\x12\xab\x01\n" +
	"\x16CreateCanaryDeployment\x12!.pod.v1alpha1.CreateCanaryRequest\x1a\".pod.v1alpha1.CreateCanaryResponse\"J\x82\xd3\xe4\x93\x02D:\x01*\"?/v1alpha1/namespaces/{namespace}/rollouts/{rollout_name}/canary\x12\xb7\x01\n" +
	"\x19CreateBlueGreenDeployment\x12$.pod.v1alpha1.CreateBlueGreenRequest\x1a%.pod.v1alpha1.CreateBlueGreenResponse\"M\x82\xd3\xe4\x93\x02G:\x01*\"B/v1alpha1/namespaces/{namespace}/rollouts/{rollout_name}/bluegreen\x12\x97\x01\n" +
	"\vPodsMetrics\x12 .pod.v1alpha1.PodsMetricsRequest\x1a!.pod.v1alpha1.PodsMetricsResponse\"C\x82\xd3\xe4\x93\x02=\x12;/v1alpha1/namespaces/{namespace}/{release_name}/pod/metricsB\x0eZ\f./pkg/pb/;pbb\x06proto3"

var (
	file_pod_service_proto_rawDescOnce sync.Once
	file_pod_service_proto_rawDescData []byte
)

func file_pod_service_proto_rawDescGZIP() []byte {
	file_pod_service_proto_rawDescOnce.Do(func() {
		file_pod_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pod_service_proto_rawDesc), len(file_pod_service_proto_rawDesc)))
	})
	return file_pod_service_proto_rawDescData
}

var file_pod_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pod_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_pod_service_proto_goTypes = []any{
	(PodState)(0),                   // 0: pod.v1alpha1.PodState
	(*Pod)(nil),                     // 1: pod.v1alpha1.Pod
	(*DeletePodRequest)(nil),        // 2: pod.v1alpha1.DeletePodRequest
	(*DeletePodResponse)(nil),       // 3: pod.v1alpha1.DeletePodResponse
	(*GetPodLogsRequest)(nil),       // 4: pod.v1alpha1.GetPodLogsRequest
	(*LogChunk)(nil),                // 5: pod.v1alpha1.LogChunk
	(*TerminalSessionInfo)(nil),     // 6: pod.v1alpha1.TerminalSessionInfo
	(*TerminalMessage)(nil),         // 7: pod.v1alpha1.TerminalMessage
	(*Resize)(nil),                  // 8: pod.v1alpha1.Resize
	(*ConfigureHPARequest)(nil),     // 9: pod.v1alpha1.ConfigureHPARequest
	(*ConfigureHPAResponse)(nil),    // 10: pod.v1alpha1.ConfigureHPAResponse
	(*ConfigureVPARequest)(nil),     // 11: pod.v1alpha1.ConfigureVPARequest
	(*ConfigureVPAResponse)(nil),    // 12: pod.v1alpha1.ConfigureVPAResponse
	(*CreateCanaryRequest)(nil),     // 13: pod.v1alpha1.CreateCanaryRequest
	(*CreateCanaryResponse)(nil),    // 14: pod.v1alpha1.CreateCanaryResponse
	(*CreateBlueGreenRequest)(nil),  // 15: pod.v1alpha1.CreateBlueGreenRequest
	(*CreateBlueGreenResponse)(nil), // 16: pod.v1alpha1.CreateBlueGreenResponse
	(*PodsMetricsRequest)(nil),      // 17: pod.v1alpha1.PodsMetricsRequest
	(*PodsMetricsResponse)(nil),     // 18: pod.v1alpha1.PodsMetricsResponse
	nil,                             // 19: pod.v1alpha1.Pod.LabelsEntry
	nil,                             // 20: pod.v1alpha1.Pod.AnnotationsEntry
	nil,                             // 21: pod.v1alpha1.ConfigureHPARequest.MetricsEntry
	nil,                             // 22: pod.v1alpha1.ConfigureVPARequest.ResourcePoliciesEntry
	nil,                             // 23: pod.v1alpha1.CreateCanaryRequest.SelectorEntry
	nil,                             // 24: pod.v1alpha1.CreateCanaryRequest.TrafficRoutingEntry
	nil,                             // 25: pod.v1alpha1.CreateBlueGreenRequest.SelectorEntry
	(*timestamppb.Timestamp)(nil),   // 26: google.protobuf.Timestamp
}
var file_pod_service_proto_depIdxs = []int32{
	0,  // 0: pod.v1alpha1.Pod.state:type_name -> pod.v1alpha1.PodState
	26, // 1: pod.v1alpha1.Pod.start_time:type_name -> google.protobuf.Timestamp
	19, // 2: pod.v1alpha1.Pod.labels:type_name -> pod.v1alpha1.Pod.LabelsEntry
	20, // 3: pod.v1alpha1.Pod.annotations:type_name -> pod.v1alpha1.Pod.AnnotationsEntry
	26, // 4: pod.v1alpha1.DeletePodResponse.deletion_timestamp:type_name -> google.protobuf.Timestamp
	26, // 5: pod.v1alpha1.LogChunk.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 6: pod.v1alpha1.TerminalMessage.session_info:type_name -> pod.v1alpha1.TerminalSessionInfo
	8,  // 7: pod.v1alpha1.TerminalMessage.resize:type_name -> pod.v1alpha1.Resize
	21, // 8: pod.v1alpha1.ConfigureHPARequest.metrics:type_name -> pod.v1alpha1.ConfigureHPARequest.MetricsEntry
	26, // 9: pod.v1alpha1.ConfigureHPAResponse.created_at:type_name -> google.protobuf.Timestamp
	22, // 10: pod.v1alpha1.ConfigureVPARequest.resource_policies:type_name -> pod.v1alpha1.ConfigureVPARequest.ResourcePoliciesEntry
	26, // 11: pod.v1alpha1.ConfigureVPAResponse.created_at:type_name -> google.protobuf.Timestamp
	23, // 12: pod.v1alpha1.CreateCanaryRequest.selector:type_name -> pod.v1alpha1.CreateCanaryRequest.SelectorEntry
	24, // 13: pod.v1alpha1.CreateCanaryRequest.traffic_routing:type_name -> pod.v1alpha1.CreateCanaryRequest.TrafficRoutingEntry
	26, // 14: pod.v1alpha1.CreateCanaryResponse.created_at:type_name -> google.protobuf.Timestamp
	25, // 15: pod.v1alpha1.CreateBlueGreenRequest.selector:type_name -> pod.v1alpha1.CreateBlueGreenRequest.SelectorEntry
	26, // 16: pod.v1alpha1.CreateBlueGreenResponse.created_at:type_name -> google.protobuf.Timestamp
	2,  // 17: pod.v1alpha1.PodManagerService.DeletePod:input_type -> pod.v1alpha1.DeletePodRequest
	4,  // 18: pod.v1alpha1.PodManagerService.GetPodLogs:input_type -> pod.v1alpha1.GetPodLogsRequest
	7,  // 19: pod.v1alpha1.PodManagerService.ExecPodTerminal:input_type -> pod.v1alpha1.TerminalMessage
	9,  // 20: pod.v1alpha1.PodManagerService.ConfigureHorizontalAutoscaling:input_type -> pod.v1alpha1.ConfigureHPARequest
	11, // 21: pod.v1alpha1.PodManagerService.ConfigureVerticalAutoscaling:input_type -> pod.v1alpha1.ConfigureVPARequest
	13, // 22: pod.v1alpha1.PodManagerService.CreateCanaryDeployment:input_type -> pod.v1alpha1.CreateCanaryRequest
	15, // 23: pod.v1alpha1.PodManagerService.CreateBlueGreenDeployment:input_type -> pod.v1alpha1.CreateBlueGreenRequest
	17, // 24: pod.v1alpha1.PodManagerService.PodsMetrics:input_type -> pod.v1alpha1.PodsMetricsRequest
	3,  // 25: pod.v1alpha1.PodManagerService.DeletePod:output_type -> pod.v1alpha1.DeletePodResponse
	5,  // 26: pod.v1alpha1.PodManagerService.GetPodLogs:output_type -> pod.v1alpha1.LogChunk
	7,  // 27: pod.v1alpha1.PodManagerService.ExecPodTerminal:output_type -> pod.v1alpha1.TerminalMessage
	10, // 28: pod.v1alpha1.PodManagerService.ConfigureHorizontalAutoscaling:output_type -> pod.v1alpha1.ConfigureHPAResponse
	12, // 29: pod.v1alpha1.PodManagerService.ConfigureVerticalAutoscaling:output_type -> pod.v1alpha1.ConfigureVPAResponse
	14, // 30: pod.v1alpha1.PodManagerService.CreateCanaryDeployment:output_type -> pod.v1alpha1.CreateCanaryResponse
	16, // 31: pod.v1alpha1.PodManagerService.CreateBlueGreenDeployment:output_type -> pod.v1alpha1.CreateBlueGreenResponse
	18, // 32: pod.v1alpha1.PodManagerService.PodsMetrics:output_type -> pod.v1alpha1.PodsMetricsResponse
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_pod_service_proto_init() }
func file_pod_service_proto_init() {
	if File_pod_service_proto != nil {
		return
	}
	file_pod_service_proto_msgTypes[6].OneofWrappers = []any{
		(*TerminalMessage_SessionInfo)(nil),
		(*TerminalMessage_Data)(nil),
		(*TerminalMessage_Resize)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pod_service_proto_rawDesc), len(file_pod_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pod_service_proto_goTypes,
		DependencyIndexes: file_pod_service_proto_depIdxs,
		EnumInfos:         file_pod_service_proto_enumTypes,
		MessageInfos:      file_pod_service_proto_msgTypes,
	}.Build()
	File_pod_service_proto = out.File
	file_pod_service_proto_goTypes = nil
	file_pod_service_proto_depIdxs = nil
}
